const INITIAL_STATE = {
  movies: [

      {id: 1,
        name: 'Capybara Island!',
        author:"Jarvan Darius",
        img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 ,
        movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},

      {id: 2, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 3, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 4, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 5, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 6, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 7, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 8, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 9, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 10, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 11, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 12, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 13, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 14, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 15, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 16, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 17, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 18, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 19, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 20, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 21, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 22, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
      {id: 23, name: 'Capybara Island!', author:"Jarvan Darius", img: "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEwMDk2Mn0", views: 133333 , movie: '<iframe src="https://www.youtube.com/embed/gOqKwCyA0QM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',},
  ]
}
const movieReducer = (state = INITIAL_STATE, action) => {
  switch(action.type){
      default:
        return state;
    }
}

export default movieReducer;